// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxduPnZbLCoIZxCJYgUIIMdZa0dGZdFLA',
    appId: '1:658094478499:web:00690f0348719f04181b16',
    messagingSenderId: '658094478499',
    projectId: 'shared-muse',
    authDomain: 'shared-muse.firebaseapp.com',
    storageBucket: 'shared-muse.appspot.com',
    measurementId: 'G-DL7WV38CGV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbosLOQ7OBo6fNH6mg9U86tUGxy3-MutE',
    appId: '1:658094478499:android:ee0e7b63408a320c181b16',
    messagingSenderId: '658094478499',
    projectId: 'shared-muse',
    storageBucket: 'shared-muse.appspot.com',
  );
}
